# Dependencies
markdown:         kramdown
highlighter:      rouge
gems: [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            Carl Lemaire
tagline:          Apprentissage profond
description:      Salut! Je fais une maîtrise en apprentissage profond (deep learning) à l'Université de Sherbrooke. Ici, je partage mes découvertes et je vulgarise.
url:              https://lemairecarl.github.io
baseurl:          /
author:           Carl Lemaire

paginate:         5
excerpt_separator: "\n\n"
