# Dependencies
markdown:         kramdown
highlighter:      rouge
gems: [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            Carl Lemaire
tagline:          Apprentissage profond
description:      Salut! Je suis analyste en algorithmes d'apprentissage chez Calcul Québec. Ici, je vulgarise l'intelligence articielle et je discute de ses impacts sur la société.
url:              https://lemairecarl.github.io
baseurl:          /
author:           Carl Lemaire

paginate:         5
excerpt_separator: "\n\n"
